EasyCashProject.PresentationLayer/Controllers/LoginController.cs
using EasyCashProject.EntityLayer.Concrete;
using EasyCashProject.PresentationLayer.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace EasyCashProject.PresentationLayer.Controllers
{
    public class LoginController : Controller
    {
        private readonly SignInManager<AppUser> _signInManager;
        private readonly UserManager<AppUser> _userManager;

        public LoginController(SignInManager<AppUser> signInManager, UserManager<AppUser> userManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(LoginViewModel loginViewModel)
        {
            var result = await _signInManager.PasswordSignInAsync
                (loginViewModel.UserName, loginViewModel.Password, false, true); // 3. deger kullanicinin bilgileri tarayicida saklanmasin, 4. deger: birden fazla sifre yanlis girildigi zaman belli bir sure giris yapma kilitlenecek
            if (result.Succeeded)
            {
                var user = await _userManager.FindByNameAsync(loginViewModel.UserName);
                if (user.EmailConfirmed == true) // Eger giris yapmak isteyen kullanicinin EmailConfirmed alani true ise basarili sekilde giris yapilmis olunacak
                {
                    return RedirectToAction("Index", "MyAccounts");
                }
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> LogOut()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

EasyCashProject.PresentationLayer/Views/Shared/Components/_CustomerLayoutNavbarPartial/Default.cshtml
<div class="top_nav">
    <div class="nav_menu">
        <nav>
            <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
            </div>

            <ul class="nav navbar-nav navbar-right">
                <li class="">
                    <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                        <img src="~/user.png" alt="">@ViewBag.loginUserName
                        <span class=" fa fa-angle-down"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-usermenu pull-right">
                        <li><a asp-controller="MyAccounts" asp-action="Index"> Profilim</a></li>
                        <li><a asp-controller="Login" asp-action="LogOut"><i class="fa fa-sign-out pull-right"></i> Çıkış Yap</a></li>
                    </ul>
                </li>

                @await Component.InvokeAsync("_NavbarNotificationListPartial")
            </ul>
        </nav>
    </div>
</div>