EasyCashProject.PresentationLayer/Models/LoginViewModel.cs
namespace EasyCashProject.PresentationLayer.Models
{
    public class LoginViewModel
    {
        public string UserName { get; set; }
        public string Password { get; set; }
    }
}

EasyCashProject.PresentationLayer/Controllers/LoginController.cs
using EasyCashProject.EntityLayer.Concrete;
using EasyCashProject.PresentationLayer.Models;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace EasyCashProject.PresentationLayer.Controllers
{
    public class LoginController : Controller
    {
        private readonly SignInManager<AppUser> _signInManager;
        private readonly UserManager<AppUser> _userManager;

        public LoginController(SignInManager<AppUser> signInManager, UserManager<AppUser> userManager)
        {
            _signInManager = signInManager;
            _userManager = userManager;
        }

        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Index(LoginViewModel loginViewModel)
        {
            var result = await _signInManager.PasswordSignInAsync
                (loginViewModel.UserName, loginViewModel.Password, false, true); // 3. deger kullanicinin bilgileri tarayicida saklanmasin, 4. deger: birden fazla sifre yanlis girildigi zaman belli bir sure giris yapma kilitlenecek
            if (result.Succeeded)
            {
                var user = await _userManager.FindByNameAsync(loginViewModel.UserName);
                if (user.EmailConfirmed == true) // Eger giris yapmak isteyen kullanicinin EmailConfirmed alani true ise basarili sekilde giris yapilmis olunacak
                {
                    return RedirectToAction("Index", "MyAccounts");
                }
            }
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> LogOut()
        {
            await _signInManager.SignOutAsync();
            return RedirectToAction("Index", "Home");
        }
    }
}

EasyCashProject.PresentationLayer/Controllers/RegisterController.cs
using EasyCashProject.DtoLayer.Dtos.AppUserDtos;
using EasyCashProject.EntityLayer.Concrete;
using MailKit.Net.Smtp;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using MimeKit;

namespace EasyCashProject.PresentationLayer.Controllers
{
	public class RegisterController : Controller
	{
		private readonly UserManager<AppUser> _userManager;

		public RegisterController(UserManager<AppUser> userManager)
		{
			_userManager = userManager;
		}

		[HttpGet]
		public IActionResult Index()
		{
			return View();
		}

		[HttpPost]
		public async Task<IActionResult> Index(AppUserRegisterDto appUserRegisterDto)
		{
			if (ModelState.IsValid)
			{
				Random random = new Random();
				int code = random.Next(100000, 1000000);
				AppUser appUser = new AppUser()
				{
					UserName = appUserRegisterDto.UserName,
					Name = appUserRegisterDto.Name,
					Surname = appUserRegisterDto.Surname,
					Email = appUserRegisterDto.Email,
					City = "Test",
					District = "Test",
					ImageUrl = "Test",
					ConfirmCode = code, // Email'e onay kodu gonderilecek ve email onaylama islemi gerceklestirilecek
				};
				var result = await _userManager.CreateAsync(appUser, appUserRegisterDto.Password);
				if (result.Succeeded)
				{
					// Eger islem basarili olursa maile onay kodu gonderilecek
					MimeMessage mimeMessage = new MimeMessage();
					MailboxAddress mailboxAddressFrom = new MailboxAddress("Easy Cash Admin", "uiswagger@gmail.com"); // Mail kimden gidecek
					MailboxAddress mailboxAddressTo = new MailboxAddress("User", appUser.Email); // Mail (onay kodu) kime gonderilecek

					mimeMessage.From.Add(mailboxAddressFrom); // Mail kimden gidecek
					mimeMessage.To.Add(mailboxAddressTo); // Mail kime gidecek

					var bodyBuilder = new BodyBuilder();
					bodyBuilder.TextBody = "Kayıt işlemini gerçekleştirmek için onay kodunuz: " + code;
					mimeMessage.Body = bodyBuilder.ToMessageBody();

					mimeMessage.Subject = "Easy Cash Onay Kodu";

					SmtpClient client = new SmtpClient();
					client.Connect("smtp.gmail.com", 587, false);
					client.Authenticate("uiswagger@gmail.com", "jmntbheiwaqqtxyy");
					client.Send(mimeMessage);
					client.Disconnect(true);

					TempData["Mail"] = appUserRegisterDto.Email; // Kayit olan kisinin mailini ConfirmMail controller'ina ve oradaki Index sayfasina tasiyabilmek icin

					return RedirectToAction("Index", "ConfirmMail"); // Kullanici sisteme kaydolduktan sonra Mail onaylama sayfasina yonlendirilecek
				}
				else
				{
					foreach (var item in result.Errors)
					{
						ModelState.AddModelError("", item.Description);
					}
				}
			}
			return View();
		}
	}
}

EasyCashProject.PresentationLayer/Views/Login/Index.cshtml
@model LoginViewModel

@{
	Layout = null;
}
<!DOCTYPE html>
<html>

<!-- Head -->
<head>

	<title>Giriş Sayfası</title>

	<!-- Meta-Tags -->
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
	<meta name="keywords" content="Existing Login Form Widget Responsive, Login Form Web Template, Flat Pricing Tables, Flat Drop-Downs, Sign-Up Web Templates, Flat Web Templates, Login Sign-up Responsive Web Template, Smartphone Compatible Web Template, Free Web Designs for Nokia, Samsung, LG, Sony Ericsson, Motorola Web Design">
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- //Meta-Tags -->

	<link href="~/register/css/popuo-box.css" rel="stylesheet" type="text/css" media="all" />

	<!-- Style -->
	<link rel="stylesheet" href="~/register/css/style.css" type="text/css" media="all">

	<!-- Fonts -->
	<link href="//fonts.googleapis.com/css?family=Quicksand:300,400,500,700" rel="stylesheet">
	<!-- //Fonts -->

</head>
<!-- //Head -->
<!-- Body -->
<body>

	<h1>Easy Cash Giriş Formu</h1>

	<div class="w3layoutscontaineragileits">
		<h2>Easy Cash</h2>
		<form method="post">
			<input type="text" asp-for="UserName" placeholder="Kullanıcı Adınız" required="">
			<input type="password" asp-for="Password" placeholder="Şifreniz" required="">
			<br /><br />
			<ul class="agileinfotickwthree">
				<li>
					<input type="checkbox" id="brand1" value="">
					<label for="brand1"><span></span>Beni Hatırla</label>
					<a asp-controller="Register" asp-action="Index">Bir Hesabınız Yok mu?</a>
				</li>
			</ul>
			<div class="aitssendbuttonw3ls">
				<input type="submit" value="Giriş Yap">
				<div class="clear"></div>
			</div>
		</form>
	</div>

	<div class="w3footeragile">
		<p> &copy; @DateTime.Now.Year EasyCash Giriş Paneli. Tüm Hakları Saklıdır | Design by <a href="http://w3layouts.com" target="_blank">W3layouts</a></p>
	</div>


	<script type="text/javascript" src="~/register/js/jquery-2.1.4.min.js"></script>


	<script src="~/register/js/jquery.magnific-popup.js" type="text/javascript"></script>

	<script>
		$(document).ready(function() {
		$('.w3_play_icon,.w3_play_icon1,.w3_play_icon2').magnificPopup({
			type: 'inline',
			fixedContentPos: false,
			fixedBgPos: true,
			overflowY: 'auto',
			closeBtnInside: true,
			preloader: false,
			midClick: true,
			removalDelay: 300,
			mainClass: 'my-mfp-zoom-in'
		});

		});
	</script>

</body>
<!-- //Body -->

</html>